import React, { useState, useEffect, useRef, useCallback } from 'react';
import { apiClient } from '../../api/client';

interface EthicalPrinciple {
  title: string;
  description: string;
}

interface EthicalAIData {
  version: string;
  title: string;
  effectiveDate: string;
  principles: EthicalPrinciple[];
  disclaimer: string;
}

interface HiringDisclaimerData {
  title: string;
  content: string;
  lastUpdated: string;
}

interface TermsSection {
  id: string;
  title: string;
  content: string;
}

const termsSections: TermsSection[] = [
  {
    id: 'account',
    title: '1. Account Terms',
    content:
      'You must be at least 16 years old to use this service. You are responsible for maintaining the security of your account credentials. You must provide accurate and complete information when creating an account. One person or entity may not maintain more than one account. You are responsible for all activity that occurs under your account.',
  },
  {
    id: 'usage',
    title: '2. Acceptable Use',
    content:
      'You agree to use the platform only for its intended purpose of interview practice and preparation. You must not attempt to reverse-engineer, decompile, or extract the AI models or algorithms. You must not use the platform to conduct actual job interviews or make real hiring decisions. You must not share your account or recordings with third parties without consent. Automated access or scraping of the platform is prohibited.',
  },
  {
    id: 'data',
    title: '3. Data & Content',
    content:
      'You retain ownership of any content you upload, including resumes and other documents. By using the platform, you grant us a limited license to process your data for the purpose of providing our services. Interview recordings and AI-generated evaluations are stored according to our data retention policy. You may request deletion of your data at any time through the account settings.',
  },
  {
    id: 'privacy',
    title: '4. Privacy & Data Protection',
    content:
      'Your use of the platform is also governed by our Privacy Policy. We collect and process personal data as described in the Privacy Policy. We implement appropriate technical and organizational measures to protect your data. We comply with applicable data protection regulations, including GDPR where applicable.',
  },
  {
    id: 'ai-disclaimers',
    title: '5. AI & Automated Processing Disclaimers',
    content:
      'AI-generated scores, feedback, and evaluations are provided for educational and practice purposes only. The platform does not make automated hiring decisions. AI evaluations may contain inaccuracies and should not be relied upon as the sole measure of interview performance. We continuously work to improve our AI models and reduce bias, but no AI system is perfect. Users should use AI feedback as one of many tools in their interview preparation.',
  },
  {
    id: 'intellectual-property',
    title: '6. Intellectual Property',
    content:
      'The platform, including its AI models, algorithms, interface design, and content, is protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works of the platform. Interview questions generated by the AI are provided for your personal practice use only.',
  },
  {
    id: 'limitation',
    title: '7. Limitation of Liability',
    content:
      'The platform is provided "as is" without warranty of any kind. We do not guarantee that AI evaluations accurately reflect real interview performance. We are not responsible for hiring outcomes or career decisions based on platform feedback. Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim.',
  },
  {
    id: 'termination',
    title: '8. Termination',
    content:
      'Either party may terminate the agreement at any time. Upon termination, your right to use the platform ceases immediately. We will delete your data in accordance with our retention policy unless you request earlier deletion. Provisions that by their nature should survive termination will remain in effect.',
  },
  {
    id: 'changes',
    title: '9. Changes to Terms',
    content:
      'We may modify these terms at any time. Material changes will be communicated via email or a prominent notice on the platform at least 30 days before taking effect. Your continued use of the platform after changes constitutes acceptance. If you disagree with changes, you may close your account.',
  },
  {
    id: 'governing-law',
    title: '10. Governing Law',
    content:
      'These terms shall be governed by and construed in accordance with applicable laws. Any disputes arising from these terms or your use of the platform shall be resolved through good-faith negotiation first, and if necessary, through binding arbitration.',
  },
];

export const TermsPage: React.FC = () => {
  const [ethicalAI, setEthicalAI] = useState<EthicalAIData | null>(null);
  const [hiringDisclaimer, setHiringDisclaimer] = useState<HiringDisclaimerData | null>(null);
  const [activeSection, setActiveSection] = useState('disclaimer-banner');

  const contentRef = useRef<HTMLDivElement>(null);
  const sectionRefs = useRef<Record<string, HTMLElement | null>>({});

  useEffect(() => {
    apiClient
      .get('/security/ethical-ai')
      .then((res) => setEthicalAI(res.data))
      .catch(() => {});
    apiClient
      .get('/security/hiring-disclaimer')
      .then((res) => setHiringDisclaimer(res.data))
      .catch(() => {});
  }, []);

  const allSectionIds = [
    'disclaimer-banner',
    'ethical-ai',
    ...termsSections.map((s) => s.id),
  ];

  const handleScroll = useCallback(() => {
    const el = contentRef.current;
    if (!el) return;

    for (let i = allSectionIds.length - 1; i >= 0; i--) {
      const sectionId = allSectionIds[i];
      const sectionEl = sectionRefs.current[sectionId];
      if (sectionEl) {
        const rect = sectionEl.getBoundingClientRect();
        const containerRect = el.getBoundingClientRect();
        if (rect.top <= containerRect.top + 100) {
          setActiveSection(sectionId);
          break;
        }
      }
    }
  }, []);

  const scrollToSection = (sectionId: string) => {
    const el = sectionRefs.current[sectionId];
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  };

  const tocItems = [
    { id: 'disclaimer-banner', title: 'Hiring Disclaimer' },
    { id: 'ethical-ai', title: 'Ethical AI Declaration' },
    ...termsSections.map((s) => ({ id: s.id, title: s.title })),
  ];

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Terms of Service</h1>
          <p className="mt-2 text-sm text-gray-500">
            Last updated: January 1, 2026 &middot; Version 1.0.0
          </p>
        </div>

        <div className="flex gap-8">
          {/* Table of Contents Sidebar */}
          <aside className="hidden lg:block w-64 flex-shrink-0">
            <nav className="sticky top-8">
              <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">
                Table of Contents
              </h3>
              <ul className="space-y-1">
                {tocItems.map((item) => (
                  <li key={item.id}>
                    <button
                      onClick={() => scrollToSection(item.id)}
                      className={`block w-full text-left px-3 py-2 text-sm rounded-md transition-colors ${
                        activeSection === item.id
                          ? 'bg-indigo-50 text-indigo-700 font-medium'
                          : 'text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 hover:text-gray-900 dark:hover:text-white'
                      }`}
                    >
                      {item.title}
                    </button>
                  </li>
                ))}
              </ul>
            </nav>
          </aside>

          {/* Main Content */}
          <div className="flex-1 min-w-0">
            <div
              ref={contentRef}
              onScroll={handleScroll}
              className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-8 max-h-[75vh] overflow-y-auto"
            >
              {/* No Automated Hiring Disclaimer Banner */}
              <section
                ref={(el) => {
                  sectionRefs.current['disclaimer-banner'] = el;
                }}
                className="mb-8"
              >
                <div className="bg-amber-50 border-l-4 border-amber-400 rounded-r-lg p-6">
                  <div className="flex items-start">
                    <div className="flex-shrink-0">
                      <svg
                        className="h-6 w-6 text-amber-500"
                        fill="none"
                        viewBox="0 0 24 24"
                        strokeWidth="1.5"
                        stroke="currentColor"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z"
                        />
                      </svg>
                    </div>
                    <div className="ml-4">
                      <h2 className="text-lg font-bold text-amber-800">
                        {hiringDisclaimer?.title || 'Important Disclaimer'}
                      </h2>
                      <p className="mt-2 text-amber-700 leading-relaxed">
                        {hiringDisclaimer?.content ||
                          'This platform is an AI-powered interview preparation tool designed for practice and self-improvement. It does NOT make automated hiring decisions. All scores, feedback, and evaluations are generated by AI models for educational purposes only and should not be used as the sole basis for employment decisions by any organization.'}
                      </p>
                      {hiringDisclaimer?.lastUpdated && (
                        <p className="mt-2 text-xs text-amber-600">
                          Last updated: {hiringDisclaimer.lastUpdated}
                        </p>
                      )}
                    </div>
                  </div>
                </div>
              </section>

              {/* Ethical AI Declaration */}
              <section
                ref={(el) => {
                  sectionRefs.current['ethical-ai'] = el;
                }}
                className="mb-10"
              >
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
                  {ethicalAI?.title || 'Ethical AI Declaration'}
                </h2>
                {ethicalAI?.effectiveDate && (
                  <p className="text-sm text-gray-500 mb-6">
                    Effective: {ethicalAI.effectiveDate} &middot; Version {ethicalAI.version}
                  </p>
                )}

                <div className="grid gap-4 sm:grid-cols-2">
                  {(ethicalAI?.principles || []).map((principle, index) => (
                    <div
                      key={index}
                      className="bg-indigo-50 border border-indigo-100 rounded-lg p-5"
                    >
                      <h3 className="font-semibold text-indigo-900 mb-2">{principle.title}</h3>
                      <p className="text-sm text-indigo-700 leading-relaxed">
                        {principle.description}
                      </p>
                    </div>
                  ))}
                </div>

                {ethicalAI?.disclaimer && (
                  <div className="mt-6 bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg p-4">
                    <p className="text-sm text-gray-600 dark:text-gray-400 italic">{ethicalAI.disclaimer}</p>
                  </div>
                )}
              </section>

              {/* Divider */}
              <hr className="my-8 border-gray-200 dark:border-gray-700" />

              {/* Terms Sections */}
              <div className="prose prose-gray max-w-none">
                <p className="text-gray-600 dark:text-gray-400 mb-8">
                  By using our platform, you agree to the following terms and conditions. Please read
                  them carefully before using our services.
                </p>

                {termsSections.map((section) => (
                  <section
                    key={section.id}
                    ref={(el) => {
                      sectionRefs.current[section.id] = el;
                    }}
                    className="mb-8"
                  >
                    <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">{section.title}</h2>
                    <p className="text-gray-700 dark:text-gray-300 leading-relaxed">{section.content}</p>
                  </section>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
