export const ERROR_CODES = {
  // Auth errors
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_2FA_REQUIRED: 'AUTH_2FA_REQUIRED',
  AUTH_2FA_INVALID: 'AUTH_2FA_INVALID',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',

  // User errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_PROFILE_NOT_FOUND: 'USER_PROFILE_NOT_FOUND',
  USER_INVALID_PASSWORD: 'USER_INVALID_PASSWORD',

  // Interview errors
  INTERVIEW_NOT_FOUND: 'INTERVIEW_NOT_FOUND',
  INTERVIEW_ALREADY_COMPLETED: 'INTERVIEW_ALREADY_COMPLETED',
  INTERVIEW_ALREADY_IN_PROGRESS: 'INTERVIEW_ALREADY_IN_PROGRESS',
  INTERVIEW_MAX_PAUSES_REACHED: 'INTERVIEW_MAX_PAUSES_REACHED',
  INTERVIEW_SESSION_EXPIRED: 'INTERVIEW_SESSION_EXPIRED',
  INTERVIEW_INVALID_STATE: 'INTERVIEW_INVALID_STATE',

  // Question errors
  QUESTION_NOT_FOUND: 'QUESTION_NOT_FOUND',
  QUESTION_CATEGORY_NOT_FOUND: 'QUESTION_CATEGORY_NOT_FOUND',

  // Voice errors
  VOICE_ANALYSIS_FAILED: 'VOICE_ANALYSIS_FAILED',
  VOICE_TRANSCRIPTION_FAILED: 'VOICE_TRANSCRIPTION_FAILED',
  VOICE_NO_AUDIO_DETECTED: 'VOICE_NO_AUDIO_DETECTED',

  // Camera errors
  CAMERA_CONSENT_REQUIRED: 'CAMERA_CONSENT_REQUIRED',
  CAMERA_ANALYSIS_FAILED: 'CAMERA_ANALYSIS_FAILED',
  CAMERA_NO_FACE_DETECTED: 'CAMERA_NO_FACE_DETECTED',

  // Evaluation errors
  EVALUATION_MODEL_NOT_AVAILABLE: 'EVALUATION_MODEL_NOT_AVAILABLE',
  EVALUATION_FAILED: 'EVALUATION_FAILED',

  // Report errors
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORT_GENERATION_FAILED: 'REPORT_GENERATION_FAILED',

  // Reliability errors
  CONNECTION_LOST: 'CONNECTION_LOST',
  AUTOSAVE_FAILED: 'AUTOSAVE_FAILED',
  SESSION_RECOVERY_FAILED: 'SESSION_RECOVERY_FAILED',

  // Validation errors
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_INPUT: 'INVALID_INPUT',

  // Rate limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Server errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // GDPR / Security
  GDPR_CONSENT_REQUIRED: 'GDPR_CONSENT_REQUIRED',
  DATA_DELETION_IN_PROGRESS: 'DATA_DELETION_IN_PROGRESS',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
