export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  TWO_FACTOR_SETUP: '/2fa-setup',
  DASHBOARD: '/dashboard',
  HISTORY: '/history',
  PROGRESS: '/progress',
  PROFILE: '/profile',
  RESUMES: '/resumes',
  PREFERENCES: '/preferences',
  SECURITY: '/security',
  INTERVIEW_SETUP: '/interview/setup',
  INTERVIEW: '/interview/:id',
  INTERVIEW_COMPLETE: '/interview/:id/complete',
  INTERVIEW_CONSENT: '/interview/:id/consent',
  REVIEW: '/review/:id',
  TRANSCRIPT: '/review/:id/transcript',
  SCORE: '/review/:id/score',
  REPORT: '/review/:id/report',
  RECOMMENDATIONS: '/recommendations',
  PRIVACY: '/privacy',
  TERMS: '/terms',
} as const;
